/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RevogridIndexRouteImport } from './routes/revogrid/index'
import { Route as GlideIndexRouteImport } from './routes/glide/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RevogridIndexRoute = RevogridIndexRouteImport.update({
  id: '/revogrid/',
  path: '/revogrid/',
  getParentRoute: () => rootRouteImport,
} as any)
const GlideIndexRoute = GlideIndexRouteImport.update({
  id: '/glide/',
  path: '/glide/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/glide/': typeof GlideIndexRoute
  '/revogrid/': typeof RevogridIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/glide': typeof GlideIndexRoute
  '/revogrid': typeof RevogridIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/glide/': typeof GlideIndexRoute
  '/revogrid/': typeof RevogridIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/glide/' | '/revogrid/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/glide' | '/revogrid'
  id: '__root__' | '/' | '/glide/' | '/revogrid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GlideIndexRoute: typeof GlideIndexRoute
  RevogridIndexRoute: typeof RevogridIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revogrid/': {
      id: '/revogrid/'
      path: '/revogrid'
      fullPath: '/revogrid/'
      preLoaderRoute: typeof RevogridIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glide/': {
      id: '/glide/'
      path: '/glide'
      fullPath: '/glide/'
      preLoaderRoute: typeof GlideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GlideIndexRoute: GlideIndexRoute,
  RevogridIndexRoute: RevogridIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
